services:
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=app_db
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d app_db']
      interval: 1s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://root:secret@database:5432/app_db?sslmode=disable
    depends_on:
      database:
        condition: service_healthy
volumes:
  data-volume:
