// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	DeleteContact(ctx context.Context, id int64) error
	GetContact(ctx context.Context, id int64) (Contact, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
